name = "secret-share"
main = "src/index.ts"
compatibility_date = "2025-02-24"

[assets]
directory = "./frontend"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "SECRET_DO", class_name = "SecretDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["SecretDurableObject"]
